### ISSUE TITLE
Proide API compliance with the native JS RegExp methods

### ISSUE THREAD

**Issue by heygrady** [mscdex/node-pcre#1]
Having PCRE is really awesome. But it's preferred that it would work as more of a drop-in replacement for the native RegExp, with the ability to use the full PCRE syntax.

The biggest issue with the current implementation is that it returns a series of offsets rather than returning the string as you might expect.

What are the chances that your PCRE module will behave more like JS native `Rexexp.exec`?

[The page for RegExp on MDN](https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/RegExp/exec)

It seems like `execAll` is the same as the global flag.

**Comment by mscdex** [comment]
I think this can be done almost entirely in js. I'm open to a pull request to add such a compatibility layer.

**Comment by alexgorbatchev** [comment]
Seems like #8 addresses this in some way.

**Comment by mscdex** [comment]
@alexgorbatchev Agreed.
