### ISSUE TITLE
error when install

### ISSUE THREAD

**Issue by 534N** [mscdex/node-pcre#10]
I'm getting the node-gyp rebuild error: 

 LIBTOOL-STATIC Release/pcre.a
libtool: unrecognized option `-static'
libtool: Try`libtool --help' for more information.
make: **\* [Release/pcre.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xiaofanyang/workspace/booking/node_modules/pcre
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! pcre@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcre@0.0.5 install script.
npm ERR! This is most likely a problem with the pcre package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pcre
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "pcre"
npm ERR! cwd /Users/xiaofanyang/workspace/booking
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/xiaofanyang/workspace/booking/npm-debug.log
npm ERR! not ok code 0

what can I do to fix this?

**Comment by mscdex** [comment]
Most likely what happened was that the Macports/Homebrew libtool was being picked up instead of Xcode's libtool. A quick way to fix this is to make sure that `/usr/bin` comes first in your `$PATH`. Try that and let me know how it goes.

**Comment by 534N** [comment]
That worked! 
Now another question... I have a regex: /Information as of (?<timestamp>\S+ \S+ \S+ \S+ \S+ UTC)/, and when I exec it on this string: Information as of MON JUN 24 19:08:06 2013 UTC, I got [ 0, 46, 18, 46, named: { timestamp: [ 18, 46 ] } ], what does this result mean? I was expecting timestamp to be "MON JUN 24 19:08:06 2013 UTC"...

**Comment by mscdex** [comment]
I initially had coded it to return the start and end indices instead of the actual string for performance reasons, but other people have also expressed interested in seeing it more like the native regexp functions that return the actual substrings. I just haven't had time yet to make it configurable or just make it always return substrings.
