### ISSUE TITLE
Segmentation fault when using JIT for some regexes

### ISSUE THREAD

**Issue by calzoneman** [mscdex/node-pcre#11]
Reproducible with the following test code on node v0.10.30 on both Arch x86_64 and Debian x86_64:

``` js
var PCRE = require('pcre').PCRE;

var a = new Array(10000).join('a');
var rx = new Array(10000).join('a?') + a;

var p = new PCRE(rx);
p.study(PCRE.PCRE_STUDY_JIT_COMPILE);
p.exec(a);
```

A 20,000 character evil regex is a pretty extreme case, but I'm worried there may be strange corner cases that could cause this with a shorter regex.

The issue does not occur using the same test code, but removing the line where the JIT is applied, which leads me to believe it might be a memory allocation error.  Memory is finite so it may not make sense to raise the limit to accommodate such a corner case, but I think the error condition should be identified and handled gracefully (perhaps throw a JS Exception?) rather than causing my node process to segfault.

Thoughts?  I'm trying to investigate the issue locally right now.

**Comment by mscdex** [comment]
I'm not able to reproduce it on Ubuntu 14.04. If I insert a `console.log('hello world');` after `p.exec(a);`, it logs it to the console in both cases.

Is there something in `ulimit -a` that's the difference perhaps?

**Comment by calzoneman** [comment]
I did some investigation, and the issue stems from explicitly calling `pcre_jit_exec` without verifying that `extra->executable_jit` is not `NULL` (`pcre_exec` performs this check before invoking the JIT).

What seems to be happening is that the JIT fails but still returns a nonnull `extra` which means that your study wrapper doesn't detect the failure.

From `deps/libpcre/pcre_study.c`, line 1503:

``` c
#ifdef SUPPORT_JIT
  extra->executable_jit = NULL;
  if ((options & PCRE_STUDY_JIT_COMPILE) != 0)
    PRIV(jit_compile)(re, extra, JIT_COMPILE);
  if ((options & PCRE_STUDY_JIT_PARTIAL_SOFT_COMPILE) != 0)
    PRIV(jit_compile)(re, extra, JIT_PARTIAL_SOFT_COMPILE);
  if ((options & PCRE_STUDY_JIT_PARTIAL_HARD_COMPILE) != 0)
    PRIV(jit_compile)(re, extra, JIT_PARTIAL_HARD_COMPILE);

  printf("is executable_jit null after study? %d\n", extra->executable_jit == NULL);
  printf("study->flags = %d\n", study->flags);
  if (study->flags == 0 && (extra->flags & PCRE_EXTRA_EXECUTABLE_JIT) == 0 &&
      (options & PCRE_STUDY_EXTRA_NEEDED) == 0)
    {
        printf("this should execute\n");
#if defined COMPILE_PCRE8
    pcre_free_study(extra);
#elif defined COMPILE_PCRE16
    pcre16_free_study(extra);
#elif defined COMPILE_PCRE32
    pcre32_free_study(extra);
#endif
    extra = NULL;
    }
#endif
  }
```

(`printf`s added by me for debugging)

The result for me is that for sufficiently large values (10k in the example I gave above), the JIT is `NULL` and `extra->flags | PCRE_EXTRA_EXECUTABLE_JIT` is `0`, but `study->flags` is nonzero so the error/cleanup code is never executed.

I'm not sure what exactly is going on in PCRE or how you're intended to handle this.  The simple solution is to check if `extra->executable_jit` is `NULL` after calling study, and if it is, then don't invoke `pcre_jit_exec`.

**Comment by calzoneman** [comment]
I was able to reproduce the issue on DigitalOcean's Ubuntu 14.04 x64 image (with nodejs installed via [nodesource](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager)).

**Comment by mscdex** [comment]
Ok, e93e0c15a2 should fix it. Can you try now and let me know if that's acceptable for you?

**Comment by calzoneman** [comment]
Seems to work for me.
