### ISSUE TITLE
Constant names have too much PCRE in them

### ISSUE THREAD

**Issue by ghost** [mscdex/node-pcre#5]
PCRE.PCRE.PCRE_CASELESS =          0x00000001;  /\* C1       _/
PCRE.PCRE.PCRE_MULTILINE =         0x00000002;  /_ C1       */
...

Why PCRE.PCRE_\* ? PCRE.\* without the PCRE_ prefix would be just fine.
Regards.

**Comment by mscdex** [comment]
They're attached the object that the binding exports. Allowing bindings to "export just one thing" like you can do with module.exports in js-land, is a new thing only supported either in 0.10 or current master (I forget which). That is the reason for the double PCRE prefix (the first to get at the binding, the second at the actual exported object). The PCRE_ prefix is there in keeping with the name from the PCRE library to make it easier for those who have used the C library before.
