### ISSUE TITLE
Provide libpcre binaries

### ISSUE THREAD

**Issue by ghost** [mscdex/node-pcre#7]
It is very inconvenient to download gigabytes of applications (visual studio, python) just to produce a binary that is ~400kb, not to mention one needs to find out the instructions elsewhere and also that installing all of this on one's system may be undesirable. Since, supposedly, you are testing/using this I guess it won't be a problem to provide the binaries also. I can contribute the windows one since I already built it.

**Comment by mscdex** [comment]
This is a broader issue that is being tackled by the node core team (especially isaacs and TooTallNate). One such github issue about this for npm can be found [here](https://github.com/isaacs/npm/issues/1891).

My view is that if you're installing this on Windows for development purposes, then you (should) probably have such tools as VS and Python already installed. If you are deploying to Windows, all you have to do is bundle your node_modules, which includes compiled addons. I usually do a similar thing when deploying (to Linux), as to avoid all compilation (including node itself).

**Comment by ghost** [comment]
> My view is that if you're installing this on Windows for development purposes, then you (should) probably have such tools as VS and Python already installed.

Why should I have C++ or Python tools if I'm developing for Node? The main problem for me though is that if I want to deploy to Linux, I need to install Linux to compile one Node module which is too much. And Mac is even bigger problem.

**Comment by rlidwka** [comment]
> My view is that if you're installing this on Windows for development purposes, then you (should) probably have such tools as VS and Python already installed.

+1, same thoughts here. Native modules require the same tools to be compiled as the node.js itself, so if you're a node developer you should already have them.

> The main problem for me though is that if I want to deploy to Linux, I need to install Linux to compile one Node module which is too much. And Mac is even bigger problem.

If you want to deploy on linux/mac, you need to have a linux/mac to test it first. And in order to test it you need a server with dev tools installed. So, you need them anyway. What's the problem?

**Comment by ghost** [comment]
I don't get your point. For me the main beauty of node is that is one single binary file, no dependencies no anything. Why would I want to compile node when they provide all sorts of binaries on their site and I don't need to hack/extend it? And if I'm JS developer I want to write code in JS I don't even need to know what compiler is. And I wouldn't need to compile the native modules, if their author provided the binaries he/she already has. Of course if I _develop_ native modules your points are valid but native modules are probably 0.1% of all node modules. And for me it is not big deal to compile C++, but it is more of a principal question. node is portable. I don't need to test on linux/mac, I only need to test on one platform because node is cross platform (with minor differences that can barely affect the JS code). Of course I would test on other os-es if I have them but this is not the point. The point is by requiring someone to download and install C++ and Python (and probably linux and other compilers on other os-es if they want to distribute a neat package) to use _JavaScript_ completely breaks the beauty and simplicity of node.

Anyway, I don't want to moan or anything, I'm thankful that mscdex did the work of binding libpcre already. The other thing is minor compared to it.

**Comment by mscdex** [comment]
I'm closing this for now as previously stated this is not a node-pcre specific issue and I prefer not to incorporate download scripts for binaries because there is no easy way to give users a choice (again, this could be solved at the npm and/or node-gyp level for everybody). Most node users/developers on *nix already have build tools installed so this is pretty much a non-issue. For Windows users, there's either mingw or VC++.
